//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace miHoYoGameDownload.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("miHoYoGameDownload.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 http://127.0.0.1:5000/api?from=debug 的本地化字符串。
        /// </summary>
        internal static string debug {
            get {
                return ResourceManager.GetString("debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://sdk-static.mihoyo.com/hk4e_cn/mdk/launcher/api/resource?key=eYd89JmJ&amp;launcher_id=18 的本地化字符串。
        /// </summary>
        internal static string genshin_china {
            get {
                return ResourceManager.GetString("genshin_china", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://sdk-os-static.mihoyo.com/hk4e_global/mdk/launcher/api/resource?&amp;key=gcStgarh&amp;launcher_id=10 的本地化字符串。
        /// </summary>
        internal static string genshin_global {
            get {
                return ResourceManager.GetString("genshin_global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://bh3-launcher-static.mihoyo.com/bh3_cn/mdk/launcher/api/resource?key=SyvuPnqL&amp;launcher_id=4 的本地化字符串。
        /// </summary>
        internal static string honkai3_china {
            get {
                return ResourceManager.GetString("honkai3_china", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://bh3-launcher-static.hoyoverse.com/bh3_global/mdk/launcher/api/resource?key=tEGNtVhN&amp;launcher_id=9 的本地化字符串。
        /// </summary>
        internal static string honkai3_global {
            get {
                return ResourceManager.GetString("honkai3_global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://api-launcher-static.mihoyo.com/hkrpg_cn/mdk/launcher/api/resource?key=6KcVuOkbcqjJomjZ&amp;launcher_id=33 的本地化字符串。
        /// </summary>
        internal static string starrail_china {
            get {
                return ResourceManager.GetString("starrail_china", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://hkrpg-launcher-static.hoyoverse.com/hkrpg_global/mdk/launcher/api/resource?key=vplOVX8Vn7cwG8yb&amp;launcher_id=35 的本地化字符串。
        /// </summary>
        internal static string starrail_global {
            get {
                return ResourceManager.GetString("starrail_global", resourceCulture);
            }
        }
    }
}
